sudo: required
language: python

python:
  - '3.7'

install:
  - "$TRAVIS_BUILD_DIR/scripts/setup.sh"

script:
  - bash -c 'echo SKIP TESTS'

deploy:
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/launch-build-k8.sh panzure-dev
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: bash $TRAVIS_BUILD_DIR/scripts/launch-build-k8.sh panzure
    on:
      tag: true

